import { TFunction } from 'i18next';
import { CommentResponse } from './api';

/**
 * Checks whether a given comment is generated by the system.
 */
export function isSystemComment(comment?: Partial<CommentResponse> | null): boolean {
  if (!comment) return false;
  if (comment.isSystem) return true;
  if (comment.authorId === null || comment.authorId === undefined) {
    if (comment.authorName === 'System') return true;
  }
  if (typeof comment.content === 'string' && comment.content.startsWith('{"key":"SYSTEM_')) {
    return true;
  }
  return false;
}

/**
 * Extracts the actor (trainer name) who triggered the system action from a system comment payload.
 */
export function getSystemCommentActor(content?: string | null): string | null {
  if (!content) return null;
  if (content.startsWith('{"key":"SYSTEM_DIVE_STATUS"') || content.startsWith('{"key": "SYSTEM_DIVE_STATUS"')) {
    try {
      const data = JSON.parse(content);
      if (data.trainer && typeof data.trainer === 'string' && data.trainer.trim().length > 0) {
        return data.trainer.trim();
      }
    } catch {
      return null;
    }
  }
  return null;
}

/**
 * Formats comment content. If the comment contains a system key payload,
 * it is localized using i18next according to the current user's language settings.
 */
export function formatCommentContent(
  content: string,
  t: TFunction | ((key: string, options?: any) => string),
  language: string = 'de'
): string {
  if (!content) return '';

  if (content.startsWith('{"key":"SYSTEM_DIVE_STATUS"') || content.startsWith('{"key": "SYSTEM_DIVE_STATUS"')) {
    try {
      const data = JSON.parse(content);
      const { status, diveCode, height, nameDe, nameEn, dive } = data;

      const isDE = language.startsWith('de');
      const localizedName = isDE ? (nameDe || nameEn) : (nameEn || nameDe);

      let diveDisplay = '';
      if (diveCode && height) {
        diveDisplay = localizedName ? `${diveCode} (${height} – ${localizedName})` : `${diveCode} (${height})`;
      } else if (dive) {
        diveDisplay = dive;
      } else if (diveCode) {
        diveDisplay = diveCode;
      }

      if (status === 'MASTERED') {
        return t('systemComments.diveStatusMastered', {
          dive: diveDisplay,
          defaultValue: `🎯 ${diveDisplay} erfolgreich gemeistert! 👏`,
        });
      } else if (status === 'LEARNING') {
        return t('systemComments.diveStatusLearning', {
          dive: diveDisplay,
          defaultValue: `💪 Training für ${diveDisplay} gestartet. Weiter so! 🚀`,
        });
      } else if (status === 'PLANNED') {
        return t('systemComments.diveStatusPlanned', {
          dive: diveDisplay,
          defaultValue: `📋 ${diveDisplay} als neues Ziel aufgenommen 🎯`,
        });
      }
    } catch {
      // Return raw content if parsing fails
      return content;
    }
  }

  return content;
}
