import { TFunction } from 'i18next';
import { CommentResponse } from './api';

/**
 * Checks whether a given comment is generated by the system.
 */
export function isSystemComment(comment?: Partial<CommentResponse> | null): boolean {
  if (!comment) return false;
  if (comment.isSystem) return true;
  if (comment.authorId === null || comment.authorId === undefined) {
    if (comment.authorName === 'System') return true;
  }
  if (typeof comment.content === 'string' && comment.content.startsWith('{"key":"SYSTEM_')) {
    return true;
  }
  return false;
}

/**
 * Formats comment content. If the comment contains a system key payload,
 * it is localized using i18next according to the current user's language settings.
 */
export function formatCommentContent(content: string, t: TFunction | ((key: string, options?: any) => string)): string {
  if (!content) return '';

  if (content.startsWith('{"key":"SYSTEM_DIVE_STATUS"') || content.startsWith('{"key": "SYSTEM_DIVE_STATUS"')) {
    try {
      const data = JSON.parse(content);
      const { status, dive, trainer } = data;
      const hasTrainer = Boolean(trainer && String(trainer).trim().length > 0);

      if (status === 'MASTERED') {
        return hasTrainer
          ? t('systemComments.diveStatusMastered', {
              dive,
              trainer,
              defaultValue: `🎯 ${dive} erfolgreich gemeistert! (von ${trainer}) 👏`,
            })
          : t('systemComments.diveStatusMasteredNoTrainer', {
              dive,
              defaultValue: `🎯 ${dive} erfolgreich gemeistert! 👏`,
            });
      } else if (status === 'LEARNING') {
        return hasTrainer
          ? t('systemComments.diveStatusLearning', {
              dive,
              trainer,
              defaultValue: `💪 Training für ${dive} gestartet. Weiter so! (von ${trainer}) 🚀`,
            })
          : t('systemComments.diveStatusLearningNoTrainer', {
              dive,
              defaultValue: `💪 Training für ${dive} gestartet. Weiter so! 🚀`,
            });
      } else if (status === 'PLANNED') {
        return hasTrainer
          ? t('systemComments.diveStatusPlanned', {
              dive,
              trainer,
              defaultValue: `📋 ${dive} als neues Ziel aufgenommen (von ${trainer}) 🎯`,
            })
          : t('systemComments.diveStatusPlannedNoTrainer', {
              dive,
              defaultValue: `📋 ${dive} als neues Ziel aufgenommen 🎯`,
            });
      }
    } catch {
      // Return raw content if parsing fails
      return content;
    }
  }

  return content;
}
